language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:28msec/boost
  - sudo add-apt-repository -y ppa:jon-severinsson/ffmpeg
  - sudo apt-get update
  - sudo apt-get install -qq boost1.50 libsdl-dev
  - sudo apt-get install -qq libswresample-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev

before_script:
  cmake .

script:
  make

branches:
  only:
    - master
notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

